In [1]:
import cv2
import os
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer
import time


pygame 2.4.0 (SDL 2.26.4, Python 3.11.3)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(r"D:\Anand Gupta\Projects\Drowsiness Detection\models\mymodel.h5")

In [3]:
mixer.init()
sound= mixer.Sound('alarm.wav')
lbl=['Close', 'Open']
path = os.getcwd()

cap = cv2.VideoCapture(0)
Score = 0
while True:
     
    ret, frame = cap.read()
    height,width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3,minSize=(25,25))
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=2)
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
        # preprocessing 
        eye= frame[ey:ey+eh,ex:ex+ew]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        print(prediction)
        
        
        # if eyes are closed
        if prediction[0][0]>0.30:
            cv2.putText(frame,'closed',(15,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>10):
                try:
                    sound.play()
                except:
                    pass
            
        # if eyes are open
        elif prediction[0][1]>0.70:
            Score = Score-1
            if (Score<0):
                Score=0
            cv2.putText(frame,"Open",(10,height-20), fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL, thickness=1,color=(255,255,255),fontScale=1,lineType=cv2.LINE_AA)
            
            cv2.putText(frame,'Score:'+str(Score),(100,height-20), fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,thickness=1,color=(255,255,255),fontScale=1,lineType=cv2.LINE_AA)
        
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()


1/1 [==============================] - 1s 985ms/step
[[0.36705938 0.6329406 ]]
1/1 [==============================] - 0s 35ms/step
[[1.4208504e-07 9.9999988e-01]]
1/1 [==============================] - 0s 34ms/step
[[0.05188242 0.9481176 ]]
1/1 [==============================] - 0s 36ms/step
[[0.7739667  0.22603327]]
1/1 [==============================] - 0s 34ms/step
[[0.43830875 0.5616912 ]]
1/1 [==============================] - 0s 34ms/step
[[2.4843841e-06 9.9999750e-01]]
1/1 [==============================] - 0s 35ms/step
[[0.27076277 0.7292372 ]]
1/1 [==============================] - 0s 34ms/step
[[0.12559989 0.8744001 ]]
1/1 [==============================] - 0s 35ms/step
[[6.4868482e-06 9.9999356e-01]]
1/1 [==============================] - 0s 38ms/step
[[0.14425366 0.8557464 ]]
1/1 [==============================] - 0s 35ms/step
[[2.2898707e-06 9.9999774e-01]]
1/1 [==============================] - 0s 44ms/step
[[0.12134257 0.8786574 ]]
1/1 [==============================] - 